services:
  vue-app:
    build: .
    container_name: tech-support-front
    ports:
      - "80:80"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - vue

networks:
  vue:
    driver: bridge