services:
  vue-app:
    build:
      context: .
      target: prod
    container_name: tech-support-front
    ports:
      - "127.0.0.1:4173:80"
    networks:
      - vue

networks:
  vue:
    driver: bridge